all:	
	clang++ -o ./bin/main ./src/main.cpp ./src/common/controls.cpp ./src/common/objloader.cpp ./src/common/shader.cpp ./src/common/texture.cpp -Wall -std=c++11 -stdlib=libc++ -lglfw -lglew -framework OpenGL

run:	
	clang++ -o ./bin/main ./src/main.cpp ./src/common/controls.cpp ./src/common/objloader.cpp ./src/common/shader.cpp ./src/common/texture.cpp -Wall -std=c++11 -stdlib=libc++ -lglfw -lglew -framework OpenGL
	./bin/main